[package]
name = "rust-ci-example"
version = "0.1.1-alpha.0"
authors = ["Walfie <walfington@gmail.com>"]
publish = false

[dependencies]

[dev-dependencies.cargo-husky]
version = "1.2.0"
default-features = false
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-test"]

