# This file contains settings for the `cargo release` plugin:
# https://github.com/sunng87/cargo-release

pre-release-commit-message = "Release version {{version}} (cargo-release)"
pro-release-commit-message = "Start next development iteration {{version}} (cargo-release)"

# Ensure we're on master before attempting to release
pre-release-hook = ["git", "checkout", "master"]

